Fix initialisation with default context
gardener/landscaper pull request #175
Opened 2021-04-15 11:28 UTC by achimweigel

**How to categorize this PR?**

/area control-plane
/kind bug
/priority 3

**What this PR does / why we need it**:
Fixes problems with root installations with no repository context.

**Which issue(s) this PR fixes**:

Assume Landscaper is configured with a default repository context. If there is a root installation without a repository context deployed, all subsequently deployed root installations will fail. The reason is that for processing new root installations, all already existing root installation are instantiated and this fails for those without a repository context.

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2021-04-16 06:24 UTC, schrodit requested changes
PR is lgtm but can you add a unit test checks that the default repository is correctly set

2021-04-16 08:14 UTC, achimweigel commented
we have added a unit test

2021-04-19 09:35 UTC, schrodit approved these changes
/lgtm

2021-04-19 09:35 UTC, schrodit commented
/test

2021-04-19 10:57 UTC, merged