Conditional imports
gardener/landscaper pull request #191
Opened 2021-05-06 10:29 UTC by Diaphteiros

**How to categorize this PR?**

/area operations
/kind enhancement
/priority 3

**What this PR does / why we need it**:
This PR makes conditional imports work as expected.

**Which issue(s) this PR fixes**:
TODO check if there are fitting issues

**Release note**:

```other operator
TODO
```

2021-05-06 11:05 UTC, Diaphteiros commented on pkg/landscaper/installations/installation.go
> +	imports := getFlattenedImports(i.Blueprint.Info.Imports)
@schrodit I'd like to have your opinion on this:
This check is called to see whether the parent satisfies all imports of the subinstallation. Before my changes, this looped over `i.Blueprint.Info.Imports` (over all direct imports of the parent) and checked whether the referenced import exists. With conditional imports, this is not enough anymore.

What I changed: It now loops over a flattened import list, which contains not only the direct import definitions of the parent, but also the conditional ones - independently of whether the condition is fulfilled or not.

The potential problem I see: This doesn't check whether the condition for conditional imports is fulfilled. So, in theory, an import definition could be found which doesn't actually exist, as it depends on another import which is not fulfilled. In practise, this shouldn't happen, as subinstallation imports that reference conditional parent imports are dynamically removed from the subinstallation template, if the condition which would provide the parent import is not fulfilled.

However, this still feels pretty 'dirty' and I'm not sure that I didn't miss a case in which this assumption breaks.
Should we build it in a way that the flattened list only contains conditional import definitions, if the corresponding condition is fulfilled? If so, how do we get the information which conditional imports are fulfilled at this point (`i.Imports` is `nil`)?
What do you think?

2021-05-07 12:32 UTC, Diaphteiros commented
/test

2021-05-17 09:03 UTC, Diaphteiros commented
/test

2021-05-19 06:54 UTC, schrodit requested changes

2021-05-19 06:54 UTC, schrodit commented on docs/usage/ConditionalImports.md
> +# Conditional Imports
can you link that guide also in the `Bllueprint.md`

2021-05-19 06:54 UTC, schrodit commented on pkg/landscaper/installations/imports/conditional_imports_test.go
> +		fakeClient, state, err = envtest.NewFakeClientFromPath("./testdata/state")
if the state is not needed you could also write
```suggestion
		fakeClient, _, err = envtest.NewFakeClientFromPath("./testdata/state")
```

2021-05-19 06:54 UTC, schrodit commented on pkg/landscaper/installations/imports/constructor.go
> +			if def.ConditionalImports != nil && len(def.ConditionalImports) > 0 {
in go slices that are nil do also have a length of `0`
```suggestion
			if len(def.ConditionalImports) > 0 {
```

2021-05-19 06:54 UTC, schrodit commented on pkg/landscaper/installations/operation.go
> +		if importDef.ConditionalImports != nil && len(importDef.ConditionalImports) > 0 {
same as above
```suggestion
		if len(importDef.ConditionalImports) > 0 {
```

2021-05-19 06:54 UTC, schrodit commented on pkg/landscaper/installations/subinstallations/helper.go
> +func (o *Operation) buildCoreImports(importList lsv1alpha1.ImportDefinitionList) ([]core.ImportDefinition, error) {
can you a dd a docstring explaining what the function is doing

2021-05-20 07:05 UTC, schrodit approved these changes
/lgtm

2021-05-25 07:05 UTC, merged