Provide CD-List for imported CD-List
gardener/landscaper pull request #340
Opened 2021-10-14 04:17 UTC by achimweigel

**How to categorize this PR?**

/area robustness
/kind bug
/priority 3

**What this PR does / why we need it**:

With this PR a component descriptor list is returned for the corresponding import data and not the contained components only. This also resolves problems with the template function `generateImageOverwrite`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix user
- problems with template generateImageOverwrite fixed
```

2021-10-14 07:09 UTC, schrodit requested changes
I guess also the docs have to be adjusted with the new format.

Can you a more concrete Release note. As we also change the blueprint interface a breaking change seems also suitable.

2021-10-14 07:09 UTC, schrodit commented on pkg/landscaper/dataobjects/cdlist.go
>  // GetData returns the targets as list of internal go maps.
can you adjust the doc to reflect the new returned value

2021-10-14 07:29 UTC, Diaphteiros requested changes
There is something weird with the test, I think.

2021-10-18 05:20 UTC, achimweigel commented on pkg/landscaper/dataobjects/cdlist.go
>  // GetData returns the targets as list of internal go maps.
I have adapted the comments

2021-10-18 05:22 UTC, achimweigel commented on pkg/landscaper/installations/imports/constructor_test.go
> +			Expect(fetchedImports).To(ContainElement(secretCDData))
I was confused the the same cds are used as top level imports as well as imports in the cd list. I fixed this.

2021-10-18 08:04 UTC, schrodit requested changes
can you also add an example to the blueprint usage docs.
 
https://github.com/gardener/landscaper/blob/master/docs/usage/Blueprints.md#deployexecutions

2021-10-19 05:11 UTC, achimweigel commented
I have added the usage of cd lists to the example

2021-10-19 08:02 UTC, Diaphteiros approved these changes
Looks good to me.

2021-10-19 10:48 UTC, schrodit approved these changes
/lgtm

2021-10-19 10:48 UTC, merged