move crdmanager to its own module
gardener/landscaper pull request #362
Opened 2021-11-03 08:45 UTC by reshnm

**How to categorize this PR?**

/area usability
/kind enhancement
/priority 3

**What this PR does / why we need it**:
This PR moves the CRD manager to its own go module.
With this change, the CRD manager can be re-used in other (external) modules like the LAAS.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-11-03 08:46 UTC, reshnm commented
/test

2021-11-03 09:15 UTC, reshnm commented
/test

2021-11-04 08:05 UTC, schrodit requested changes
For the submodule to work correctly you also have to adjust some more files:
1. The pipelines file to generate another tag on release https://github.com/gardener/landscaper/blob/master/.ci/pipeline_definitions#L93 (this is needed for go submodules)
2. The go.mod altering files for releases and the next version (this is needed so that consuming modules do not ned to manually set a go.mod overwrite(`require`))
https://github.com/gardener/landscaper/blob/master/.ci/next_version#L23
https://github.com/gardener/landscaper/blob/master/.ci/release#L23

2021-11-04 09:31 UTC, reshnm commented on crdmanager/pkg/crdmanager/crdmanager.go
> +	readerBufferSize = 32
I think the name is a bit misleading. It is more of a parser read ahead size to determine wether the crd file is of type yaml or json.
I will rename it and increas its size to 1024. That should be safe.

2021-11-04 09:34 UTC, reshnm commented on crdmanager/pkg/crdmanager/crdmanager.go
> +}
I have inlined the function.

2021-11-04 09:46 UTC, reshnm commented
> For the submodule to work correctly you also have to adjust some more files:
> 
>     1. The pipelines file to generate another tag on release https://github.com/gardener/landscaper/blob/master/.ci/pipeline_definitions#L93 (this is needed for go submodules)
> 
>     2. The go.mod altering files for releases and the next version (this is needed so that consuming modules do not ned to manually set a go.mod overwrite(`require`)).
>        https://github.com/gardener/landscaper/blob/master/.ci/next_version#L23
>        https://github.com/gardener/landscaper/blob/master/.ci/release#L23
> 
> 
> Specifically these files need to be changed so that
> 
>     * the dependency towards the CRD manager in the landscaper's go.mod file is updated
> 
>     * the dependency towards the api in the CRD manager's go.mod file is updated

Thanks for pointing that out.
We just need to update the landscaper go.mod file, since the crdmanager is not used by the apis module.
Does it look good now?

2021-11-04 09:46 UTC, reshnm commented
/test

2021-11-04 09:50 UTC, reshnm commented on crdmanager/pkg/crdmanager/crdmanager.go
> +	readerBufferSize = 32
I decided to stick with the name `readerBufferSize` as the parser API uses the same name.

2021-11-04 11:13 UTC, schrodit commented
> > For the submodule to work correctly you also have to adjust some more files:
> > ```
> > 1. The pipelines file to generate another tag on release https://github.com/gardener/landscaper/blob/master/.ci/pipeline_definitions#L93 (this is needed for go submodules)
> > 
> > 2. The go.mod altering files for releases and the next version (this is needed so that consuming modules do not ned to manually set a go.mod overwrite(`require`)).
> >    https://github.com/gardener/landscaper/blob/master/.ci/next_version#L23
> >    https://github.com/gardener/landscaper/blob/master/.ci/release#L23
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Specifically these files need to be changed so that
> > ```
> > * the dependency towards the CRD manager in the landscaper's go.mod file is updated
> > 
> > * the dependency towards the api in the CRD manager's go.mod file is updated
> > ```
> 
> Thanks for pointing that out. We just need to update the landscaper go.mod file, since the crdmanager is not used by the apis module. Does it look good now?

I meant that you also have to adopt the crd manager's go.mod file like the following.
This is because it also used the landscaper api module just like the landscaper itself.
```
sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis v0.0.0-00010101000000-000000000000@}" \
  ${SOURCE_DIR}/crdmanager/go.mod
```

2021-11-04 11:41 UTC, reshnm commented
> > > For the submodule to work correctly you also have to adjust some more files:
> > > ```
> > > 1. The pipelines file to generate another tag on release https://github.com/gardener/landscaper/blob/master/.ci/pipeline_definitions#L93 (this is needed for go submodules)
> > > 
> > > 2. The go.mod altering files for releases and the next version (this is needed so that consuming modules do not ned to manually set a go.mod overwrite(`require`)).
> > >    https://github.com/gardener/landscaper/blob/master/.ci/next_version#L23
> > >    https://github.com/gardener/landscaper/blob/master/.ci/release#L23
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Specifically these files need to be changed so that
> > > ```
> > > * the dependency towards the CRD manager in the landscaper's go.mod file is updated
> > > 
> > > * the dependency towards the api in the CRD manager's go.mod file is updated
> > > ```
> > 
> > 
> > Thanks for pointing that out. We just need to update the landscaper go.mod file, since the crdmanager is not used by the apis module. Does it look good now?
> 
> I meant that you also have to adopt the crd manager's go.mod file like the following. This is because it also used the landscaper api module just like the landscaper itself.
> 
> ```
> sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis v0.0.0-00010101000000-000000000000@}" \
>   ${SOURCE_DIR}/crdmanager/go.mod
> ```

got it

2021-11-05 08:26 UTC, schrodit approved these changes
looks good from my side

2021-11-05 09:05 UTC, merged