Pass context 2
gardener/landscaper pull request #392
Opened 2022-01-11 09:43 UTC by reshnm

**How to categorize this PR?**

This PR is a follow-up of PR #372 since the original PR can't no longer be modified. 

/area deployers
/priority 3

**What this PR does / why we need it**:

The context reference specified in the installation is now passed to the subinstallations, execution and deploy items.
With that it is now possible for the deployers to use namespaced secrets to access oci or other artifacts.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
The context reference is not properly passed to all DeployItems and subinstallations.
With that the deployers are now able to use the secrets defined in the Context to access remote artifacts.
This is especially useful for multi-tenant scenarios where everything should isolated by the namespace.

```

2022-01-11 09:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/landscaper?pullRequest=392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gardener/landscaper?pullRequest=392) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: reshnm<br/>:x: Tim Schrodi<br/><hr/>**Tim Schrodi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/landscaper?pullRequest=392) it.</sub>

2022-01-12 08:34 UTC, reshnm commented
/test

2022-01-12 10:55 UTC, reshnm commented
/test

2022-01-12 13:23 UTC, reshnm commented
/test

2022-01-12 14:22 UTC, reshnm commented
/test

2022-01-12 14:31 UTC, reshnm commented
/test

2022-01-12 15:28 UTC, Diaphteiros requested changes
I made a few comments. Most of them are just minor nits referring to wrong comments on the new context fields (comment still talks about installations, probably a copy-paste error). Some of the places where I marked this (and those where I didn't mark this) are auto-generated during `make generate`, I think.

2022-01-13 08:02 UTC, reshnm commented on pkg/deployer/manifest/controller.go
>  	manifest, err := New(logger, d.lsClient, d.hostClient, &d.config, di, target)
It seems that it is the latter. The context is not used for handling kubernetes manifests.
I marked the parameter as unused.

2022-01-13 08:18 UTC, reshnm commented
/test

2022-01-13 09:27 UTC, reshnm commented
/test

2022-01-13 10:18 UTC, Diaphteiros requested changes
Found another two, seems they didn't get overwritten by `make generate`...

2022-01-13 10:18 UTC, Diaphteiros commented on pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_deployitems.yaml
> +                description: Context defines the current context of the installation.
```suggestion
                description: Context defines the current context of the deployitem.
```

2022-01-13 10:18 UTC, Diaphteiros commented on pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
> +                description: Context defines the current context of the installation.
```suggestion
                description: Context defines the current context of the execution.
```

2022-01-13 12:01 UTC, Diaphteiros approved these changes
/lgtm

2022-01-13 12:32 UTC, merged