order subinstallations by dependencies
gardener/landscaper pull request #413
Opened 2022-02-08 15:58 UTC by Diaphteiros

**How to categorize this PR?**

/area robustness
/kind bug
/priority 2

**Which issue(s) this PR fixes**:
Fixes #409 

**Release note**:

```bugfix user
Landscaper now takes dependencies into account when applying subinstallations. Before, they were applied in the order they were given in, which could mean that a subinstallation that depends on another one was updated and processed by the landscaper before the one it depends on was updated, making simultaneous updates of multiple components impossible.
```

2022-02-09 15:49 UTC, Diaphteiros commented
I had another interesting idea how to solve the linked issue, without having to order the subinstallations (which is somewhat complicated):

Imagine each subinstallation has an `observedGeneration` field for its parent, either in a label or in its status. Currently, when deciding if an installation can run, the landscaper checks whether all installations it depends on are up-to-date and Succeeded. If we extend this check to also compare the parent's `generation` - for installations which have parents - with the `observedGeneration` of the dependency, we would know if it has already been updated or not.

Pro:
- no complex logic for ordering subinstallations required

Con:
- an additional status field or label needed
  - To me it feels like this belongs into the status, but since the status is a subresource and cannot be updated at the same time as the resource itself, a label would be easier to implement and it would not require an api change.
- whenever a parent installation is changed, _all_ subinstallations have to be modified (to adapt the `observedGeneration`), instead of only those which changed

What do you think? @achimweigel @robertgraeff @reshnm

2022-02-09 16:15 UTC, robertgraeff commented
This means: if a subinstallation sees that its sibling satisfies the condition `sibling.observedParentGeneration == parent.generation` then it can be sure that the sibling has already been updated. 
Clever! I like this idea.

2022-02-09 16:20 UTC, robertgraeff commented
But what if the subinstallations must be processed again because the parent gives them changed import values. The specs/generations of the parent and the subinstallations remain unchanged, just the dataobjects are updated. Is there then a similar problem concerning the order in which the dataobjects are updated?

2022-02-10 07:57 UTC, Diaphteiros commented
@robertgraeff Good catch! I suppose you are right, if the parent gets triggered due to changed imports, its spec won't change and its generation won't change either, so we have the same problem again.
We could resolve this by making the parent's 'generation' not only its generation, but a hash containing its generation as well as its import generations or something like this, but that makes this idea somewhat ugly and complicated ...

2022-02-10 08:28 UTC, achimweigel commented
What about this: If the spec or the input data of the installation for the aggregated blueprint have changed, a new run-number for the installation is generated. This run number is provided to the subinstallations and a subinstallation which is finished gets this run number in its status. Then subinstallations only starts if their predecessors succeeded and have the run number of the parent installation in their status.

2022-02-10 09:59 UTC, Diaphteiros commented
@achimweigel So, the 'run number' is basically just like the generation, but it also contains the imports' generations?
This has the disadvantage that we need to add another field to the installation status, but the logic for checking if everything is up-to-date becomes easier.

The question is whether this solution is still 'better' than ordering the subinstallations according to their dependencies. The ordering itself is complex, but it is completely hidden from the end user, while the idea with the run numbers will add two more numbers to the status of an installation - a `runGeneration` and an `observedParentRunGeneration` - which are visible to the users. It still keeps the problem, that we now have to touch every subinstallation for every update, even if nothing changed, which we currently don't have to do.

I think there is no really nice solution for this, so we need to decide what the 'least ugly' solution is ...

2022-02-10 11:54 UTC, achimweigel commented
Yes the generation number includes somehow import changes. It does not need to reflect all changes. It is sufficient if the number changes if a reconcile starts with changed spec of imports. 

Do you really resolve all problems by just ordering the subinstallations according to their dependencies? If they are just updated in this order, you still have the problem with race conditions. If the spec of inst1 and inst3 were modified and inst1 was just reconciled with new data for inst2 but inst2 has not started yet. At this time, some inst3 depending on data of inst2 might think it could already start. Or do I miss here something?

2022-02-10 12:15 UTC, achimweigel commented
Another advantage of using such a new-generation-number of the parent installation is, that for an installation to start, it only needs to check its immediate predecessors. No recursive check of all ancestors is needed. And yes also for sub installations with no new reconcile loop (no import or spec changes), this new-generation-number has to be added to its status. A modification of the status of such sub installations is anyhow helpful, e.g. by adding some entry when it was checked the last time. In case of an erroneous behaviour we could see if that was due to a logic error or just by the fact that the item was not checked anymore.

2022-02-10 13:20 UTC, Diaphteiros commented
The idea, that only the direct dependencies need to be checked and not the transitive ones, only holds for subinstallations. For root components which depend on one another, we still have to check the transitive dependencies.

2022-02-11 05:55 UTC, achimweigel commented
That's true, but I though we discuss here in the context of aggregated blueprints? I fear for root installations we need another approach, because of a missing surrounding unit.

2022-02-14 08:03 UTC, Diaphteiros commented
You are right there, but I would try to avoid significant differences in the "am I allowed to run" logic between root installations and subinstallations. Checking an additional field for subinstallations, which doesn't exist for root installations, is not a significant change to the logic. But checking transitive dependencies in one case and only direct ones in another is a bigger difference. At least it 'feels' like this to me. 

There are two reasons for trying to keep the logic mostly identical:
1. A conceptual one: aggregated installations are meant as an instrument to group installations, not as a new entity. So multiple subinstallations should behave the same way as multiple root installations, since it is basically the same.
2. A practical one: if we have different code paths for both cases, we have to maintain two implementations for the same functionality. This also increases the chance of making mistakes in one of them, which leads to weird errors that only occur for either subinstallations or root installations.

What do you think?

2022-02-16 06:04 UTC, achimweigel commented
Not sure. From our discussion I thought that sub installations in aggregated blueprints are something different than root installations.  I understand your arguments and it would be perfect if the system behaves equal on both cases and is based on one code line but I think the most important goal is a system behaviour which is easy to understand and use. Let us see what comes out in our discussion today in the team meeting :-)

2022-02-21 11:59 UTC, Diaphteiros commented
The idea of an aggregated blueprint is that it behaves to the outside as a single component does. On the inside, it 'does stuff', which can be expressed in multiple installations that build up the whole deployment. This is pretty much the same as happens on root level. Subinstallations were not intended to differ from root installations in any way except for the scope/context. The Landscaper can perform some additional operations, since it knows the entire system of an aggregated blueprint (opposed to root-level installations, where there is no enclosing mechanism), but the core logic should be equivalent for root-level and nested installations.

2022-02-22 07:44 UTC, Diaphteiros commented
/test

2022-02-22 08:37 UTC, Diaphteiros commented
/test

2022-02-22 09:28 UTC, Diaphteiros commented
/test

2022-03-01 12:49 UTC, reshnm requested changes

2022-03-04 10:19 UTC, Diaphteiros commented
/test

2022-03-07 10:00 UTC, reshnm requested changes

2022-03-07 11:58 UTC, Diaphteiros commented on pkg/utils/cyclicdependencies.go
> +	if dc.IsClosed() {
You are right, I added the check.

2022-03-07 13:30 UTC, reshnm approved these changes
/lgtm

2022-03-08 13:41 UTC, merged