rework component version overwrites
gardener/landscaper pull request #430
Opened 2022-03-02 11:59 UTC by Diaphteiros

**How to categorize this PR?**

/area usability
/kind enhancement
/priority 3

**What this PR does / why we need it**:
The 'old' component overwrites were specified cluster-wide, opposed to all other configurations where Landscaper assumes a namespace to be an independent tenant.

To solve this in a backward compatible manner, the old implementation has not been changed. It still works as before, but is deprecated now. A new namespace-scoped resource called `ComponentVersionOverwrites` has been introduced, which looks similar to the old format, although there are some differences in behaviour.

**Special notes for your reviewer**:
Not finished yet, open TODOs:
- [ ] write unit tests for the overwrite logic
- [ ] documentation

**Release note**:

```other operator
TODO
```

2022-03-02 12:00 UTC, Diaphteiros commented
cc @mandelsoft @reshnm

2022-09-22 09:28 UTC, Diaphteiros commented
/test

2022-09-22 14:43 UTC, Diaphteiros commented
/test

2022-09-23 06:39 UTC, Diaphteiros commented
/test

2022-09-26 14:42 UTC, Diaphteiros commented
/test

2022-09-29 12:28 UTC, reshnm requested changes
To me the whole concept of the component overwrites sounds much too complex to use.
I would like to have a seperate talk about what we want to achieve whith this concept and then find an easy-to-use solution.

2022-09-29 12:28 UTC, reshnm commented on apis/core/v1alpha1/types_component_version_overwrite.go
> +// ComponentVersionOverwrites are resources that can hold any kind json or yaml data.
This comment seems like a copy/paste error?

2022-09-29 12:28 UTC, reshnm commented on docs/usage/ComponentOverwrites.md
> +This means that more specific overwrite specifications should be placed before more generic ones and if a substitution already replaced an attribute, more general substitutions later on, affecting th
Could you maybe add examples for this?
I think I get what you are saying, however, having examples would help alot.

2022-09-29 12:28 UTC, reshnm commented on docs/usage/ComponentOverwrites.md
> +A component overwrite object is a cluster-wide specification of component version overwrites. There might be any number of such overwrite objects. The described overwrite specifications are concatena
Sry to say this, but this sounds like a nightmare to use and to debug :-(

2022-09-29 12:28 UTC, reshnm commented on apis/core/types_component_version_overwrite.go
> +// SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors.
nit

2022-10-14 11:27 UTC, Diaphteiros commented
/test

2022-10-20 12:30 UTC, Diaphteiros commented
/test

2022-10-20 13:03 UTC, Diaphteiros commented
/test

2022-10-20 15:15 UTC, Diaphteiros commented
/test

2022-10-20 15:35 UTC, Diaphteiros commented
/test

2022-10-24 14:49 UTC, Diaphteiros commented
/test

2022-10-25 07:44 UTC, Diaphteiros commented
/test

2022-10-25 08:28 UTC, Diaphteiros commented
/test

2022-10-26 09:20 UTC, reshnm approved these changes
/lgtm

2022-10-26 11:47 UTC, merged