Helm deployer Int Test
gardener/landscaper pull request #609
Opened 2022-09-30 07:38 UTC by enrico-kaack-comp

**How to categorize this PR?**

/area helm-deployer
/kind test

**What this PR does / why we need it**:

Add tests for helm deployer (real helm deployer and helm templating deployer each):
- create a deployment
- update a deployment
- export a value
- readiness Check Ready (skipped for real helm deployer due to bug #600 )

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other developer
- integration test for helm deployer
```

2022-09-30 13:36 UTC, robertgraeff requested changes

2022-09-30 13:36 UTC, robertgraeff commented on test/integration/deployers/helmdeployer/helm_deployer_tests.go
> +	. "github.com/onsi/ginkgo"
Achim has updated ginkgo to ginkgo/v2:

```suggestion
	. "github.com/onsi/ginkgo/v2"
```

2022-09-30 13:50 UTC, robertgraeff requested changes

2022-10-04 08:12 UTC, enrico-kaack-comp commented on test/integration/deployers/helmdeployer/helm_deployer_tests.go
> +				di := deployDeployItemAndWaitForSuccess(ctx, f, state.State, deployName, chartDir, valuesFile, nil, &readinesCheck, realHelmDeployer)
good catch thank you. I missed that during refactoring.

2022-10-04 08:32 UTC, robertgraeff approved these changes

2022-10-10 04:46 UTC, achimweigel approved these changes
/lgtm

2022-10-11 11:33 UTC, merged