Component Model
gardener/landscaper pull request #722
Opened 2023-03-28 12:26 UTC by robertgraeff

**How to categorize this PR?**

/area oci
/kind task
/priority 3

**What this PR does / why we need it**:

This pull request hides all read operations from an OCI registry, helm chart repository etc. behind a facade.
The purpose of the facade is to simplify the integration of OCM in the Landscaper. 

For example, the following operations will be "behind" the facade:

- reading a component descriptor and blueprint in the installation controller;
- reading a helm chart from an OCI registry or helm chart repository in the helm deployer;
- reading a JSON schema during the templating of deploy items;
- reading the component descriptor in the container deployer.

The facade is contained in package `pkg/components/model`.
The current implementation is in package `pkg/components/cnudie`.
Later another OCM-based implementation can be provided.

Package `pkg/components/registries` contains another implementation of the facade. It should make the switch between the cnudie and ocm implementations, i.e. it just delegates to one of the "real" implementations.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature developer
- a facade has been introduced that encapsulates the accesses to OCI registries and Helm chart repositories 
```

2023-05-22 11:22 UTC, robertgraeff commented
Integration test has not yet  run.

2023-05-23 02:38 UTC, achimweigel requested changes
really cool stuff - only some minor points (but very hard to review)

2023-05-23 02:38 UTC, achimweigel commented on pkg/components/testutils/componentversion.go
> +type TestComponentVersion struct {
Why do we need this type? Isn't it the same as the one in .../cnudie/componentversion.go

2023-05-23 02:38 UTC, achimweigel commented on pkg/landscaper/installations/builder.go
> +			return nil, err
Looks much better but I fear I could not really verify this :-)

2023-05-23 02:38 UTC, achimweigel commented on pkg/landscaper/registry/components/oci.go
>  func NewOCIRegistryWithOCIClient(log logging.Logger, client ociclient.Client, predefinedComponentDescriptors ...*cdv2.ComponentDescriptor) (TypedRegistry, error) {
I'm wondering why NewOCIRegistryWithOCIClient is not in the components/cnudie package?

2023-05-25 08:20 UTC, achimweigel approved these changes
/lgtm

2023-05-25 08:20 UTC, achimweigel approved these changes
/lgtm

2023-05-25 08:20 UTC, merged