improve webhook logs
gardener/landscaper pull request #790
Opened 2023-07-18 11:27 UTC by Diaphteiros

**How to categorize this PR?**

/area quality
/kind regression
/priority 3

**What this PR does / why we need it**:
Improves the webhook server's logs.

**Release note**:

```other operator
TODO
```

2023-07-19 02:36 UTC, achimweigel requested changes

2023-07-19 02:36 UTC, achimweigel commented on pkg/utils/webhook/webhook.go
> +	logger.Info("Allowed request")
Might this log to info flood the logs? Perhaps in the good case debug is sufficient.

2023-07-19 02:36 UTC, achimweigel commented on pkg/utils/webhook/webhook.go
> +	logger.Info("Allowed request")
same as above

2023-07-19 02:36 UTC, achimweigel commented on pkg/utils/webhook/webhook.go
> +	logger.Info("Allowed request")
same as above

2023-07-19 02:36 UTC, achimweigel commented on pkg/utils/webhook/webhook.go
> +	logger.Info("Allowed request")
same as above

2023-08-22 13:01 UTC, Diaphteiros commented
This became obsolete with #803

2023-08-22 13:01 UTC, closed without merging