Pipeline fix
gardener/landscaper pull request #836
Opened 2023-09-28 15:12 UTC by fabianburth

**How to categorize this PR?**

/area TODO
/kind TODO
/priority 3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2023-09-28 16:50 UTC, morri-son approved these changes

2023-09-29 06:42 UTC, Diaphteiros requested changes
Small copy-paste error, otherwise lgtm.

2023-09-29 06:42 UTC, Diaphteiros commented on .ci/pipeline_definitions
> +          output_dir: 'integration_test_ocm'
```suggestion
          output_dir: 'integration_test_cnudie'
```

2023-09-29 06:56 UTC, fabianburth commented on .ci/pipeline_definitions
> +          output_dir: 'integration_test_ocm'
Good catch, thanks!

2023-09-29 06:59 UTC, Diaphteiros approved these changes
/lgtm

2023-09-29 08:15 UTC, merged