Log read ops
gardener/landscaper pull request #915
Opened 2023-12-05 11:59 UTC by achimweigel

**How to categorize this PR?**

/area deployers
/kind enhancement
/priority 3

**What this PR does / why we need it**:

Log read ops on debug level. This is a prerequisite for optimising the synchronisation.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
- log red ops
```

2023-12-05 17:34 UTC, robertgraeff requested changes

2023-12-05 17:34 UTC, robertgraeff commented on pkg/utils/read_write_layer/read.go
> +	log.Debug("ReadLayer list: + msg")
`+ msg`  should be outside the string.

2023-12-05 17:34 UTC, robertgraeff commented on pkg/utils/read_write_layer/read.go
> +	return list(ctx, c, syncObjects, readID, "dyncObjects", opts...)
Typo: `dyncObjects`

2023-12-06 06:42 UTC, achimweigel commented on pkg/utils/read_write_layer/read.go
> +	return list(ctx, c, syncObjects, readID, "dyncObjects", opts...)
fixed

2023-12-06 07:27 UTC, robertgraeff approved these changes

2023-12-06 09:59 UTC, merged