frontmatter for target-maps and some link fixes
gardener/landscaper pull request #995
Opened 2024-02-29 14:27 UTC by In-Ko

**What this PR does / why we need it**:
Adjusted the new target maps docu for the docu generation.

2024-02-29 14:55 UTC, robertgraeff approved these changes

2024-03-01 06:44 UTC, achimweigel requested changes

2024-03-01 06:44 UTC, achimweigel commented on docs/guided-tour/target-maps/01-multiple-deploy-items/README.md
> -# Multiple Deploy Items Example
This title got lost. We should keep it as in the other readme files.

2024-03-01 09:01 UTC, achimweigel approved these changes

2024-03-01 09:59 UTC, achimweigel commented
@In-Ko something went wrong. Could you retrigger the build, e.g. by another commit.

2024-03-01 12:35 UTC, merged